# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for github actions
  - package-ecosystem: 'github-actions'
    # For GitHub Actions the default location (.github/workflows) can be referenced with "/"
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '10:00'
    groups:
      all-actions:
        patterns: [ '*' ]
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/server'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '10:00'
    groups:
      major-version:
        applies-to: version-updates
        update-types: ['version-update:semver-major']
      minor-and-patch-version:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      major-security:
        applies-to: security-updates
        update-types: ['security-update:semver-major']
      minor-and-patch:-security:
        applies-to: security-updates
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 10
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/client'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '10:00'
      groups:
      major-version:
        applies-to: version-updates
        update-types: ['version-update:semver-major']
      minor-and-patch-version:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      major-security:
        applies-to: security-updates
        update-types: ['security-update:semver-major']
      minor-and-patch:-security:
        applies-to: security-updates
        update-types:
          - 'minor'
          - 'patch'
