# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'node'
  
      # Navigate to the server folder
      - name: Change directory to server
        run: cd server

      # Install dependencies in the server directory
      - name: Install dependencies
        run: npm install
        working-directory: ./server

      # Lint for server
      - name: Lint code
        run: npm run lint
        working-directory: ./server

      # Run the tests
      - name: Run tests
        run: npm run test --if-present
        working-directory: ./server

      # Optionally run build if you have a build step
      - name: Run build 
        run: npm run build --if-present
        working-directory: ./server
