# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout server source code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }} for server
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory to server
        run: cd server

      # Install dependencies in the server directory
      - name: Install dependencies
        run: npm ci 
        working-directory: ./server

      # Lint for server
      - name: Lint code
        run: npm run lint
        working-directory: ./server

      # Run the tests
      - name: Run tests
        run: npm run test --if-present
        working-directory: ./server

      # Optionally run build if you have a build step
      - name: Run build
        run: npm run build --if-present
        working-directory: ./server

  client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout client source code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }} for client
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory to client
        run: cd client

      # Install dependencies in the client directory
      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Lint code
        run: npm run lint
        working-directory: ./client

      - name: Run tests
        run: npm run test --if-present
        working-directory: ./client

      - name: Run build
        run: npm run build --if-present
        working-directory: ./client
